# Generated by Django 6.0 on 2026-03-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_user',
            field=models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='users.clinicuser'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='clinic_user',
            field=models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to='users.clinicuser'),
        ),
    ]
