# Generated by Django 6.0 on 2026-03-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_assistant', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsummary',
            name='doctor_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clinicuser'),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to='users.clinicuser'),
        ),
        migrations.AddField(
            model_name='triagemessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='health_assistant.triagesession'),
        ),
        migrations.AddField(
            model_name='clinicalsummary',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health_assistant.triagesession'),
        ),
    ]
