# Generated by Django 6.0 on 2026-03-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_registration_no', models.CharField(max_length=100, unique=True)),
                ('specialty', models.CharField(max_length=255)),
                ('qualifications', models.TextField(help_text='e.g., MBBS, MD (Cardiology)')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bio', models.TextField(blank=True)),
                ('availability_schedule', models.JSONField(default=dict, help_text='Weekly availability matrix')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g., Diabetes, Hypertension')),
                ('current_medications', models.TextField(blank=True)),
            ],
        ),
    ]
